[package]
name = "stefn-macros"
version = "0.1.0"
description = "Macros for stefn"
license.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0.89"
